# .github/workflows/test.yml
name: Run Jest Tests

on:
  push:
    branches:
      - main   # Ejecuta las pruebas cuando haya un push a la rama 'main'
  pull_request:
    branches:
      - main   # Ejecuta las pruebas en pull requests a la rama 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Define la versión de Node.js a utilizar

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
